apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-controller-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-controller-clusterrole
subjects:
  - kind: ServiceAccount
    name: pod-controller-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-controller
  template:
    metadata:
      labels:
        app: pod-controller
    spec:
      serviceAccountName: pod-controller-sa
      containers:
        - name: pod-controller
          image: thinktan/pod-controller:v4
          imagePullPolicy: Always
